services:
  ibkr:
    image: ghcr.io/extrange/ibkr:stable  # Use 'stable' tag or specific version like 'latest'
    container_name: ibkr-gateway
    environment:
      - USERNAME=${IBKR_USERNAME}
      - PASSWORD=${IBKR_PASSWORD}
      - GATEWAY_OR_TWS=${GATEWAY_OR_TWS:-gateway}
      - IBC_TradingMode=${TRADING_MODE:-paper}      
      - IBC_AcceptNonBrokerageAccountWarning=yes
    ports:
      - "127.0.0.1:6080:6080"  # noVNC browser access
      - "127.0.0.1:8888:8888"  # API access (paper trading)
      - "127.0.0.1:7497:7497"  # API access (paper trading - alternative port)
      - "127.0.0.1:7496:7496"  # API access (live trading)
    ulimits:
      nofile: 10000
    restart: unless-stopped
    volumes:
      - ibkr_settings:/home/ibkr/settings

  rebalancer-api:
    build: .
    container_name: rebalancer-api
    environment:
      - IBKR_HOST=ibkr
      - IBKR_PORT=${IBKR_PORT:-8888}
      - IBKR_CLIENT_ID=${IBKR_CLIENT_ID:-1}
      - ACCOUNT_TYPE=${TRADING_MODE:-paper}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}      
    ports:
      - "8000:8000"
    depends_on:
      - ibkr
    restart: unless-stopped

volumes:
  ibkr_settings: