x-system-version: &system-version "1.0.2"

volumes:
  ib_data:
  redis_data:

networks:
  ibkr-network:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: America/New_York
    command: redis-server --appendonly yes
    networks:
      - ibkr-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ibkr:
    image: gnzsnz/ib-gateway:latest
    ports:
      - "127.0.0.1:4001:4003"
      - "127.0.0.1:4002:4004"
      - "127.0.0.1:5900:5900"    
    environment:
      TWS_USERID: ${IB_USERNAME}
      TWS_PASSWORD: ${IB_PASSWORD}
      TWS_USERID_PAPER: ${IB_USERNAME}
      TWS_PASSWORD_PAPER: ${IB_PASSWORD}
      TWOFA_DEVICE: IB Key
      TRADING_MODE: ${TRADING_MODE:-paper}
      READ_ONLY_API: no
      BYPASS_WARNING: yes
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-10:00 PM}
      TWOFA_TIMEOUT_ACTION: restart
      RELOGIN_AFTER_TWOFA_TIMEOUT: yes
      VNC_SERVER_PASSWORD: ${VNC_PASSWORD:-password}
      TIME_ZONE: America/New_York
      TZ: America/New_York
      JAVA_HEAP_SIZE: 1024
    volumes:
      - ib_data:/home/ibgateway
      - /etc/localtime:/etc/localtime:ro
    healthcheck:      
      test: ["CMD", "sleep", "60"] # wait for 1 minute to fpr gateway to complete login workflow
      interval: 5s
      timeout: 70s # must be greater than sleep time
    networks:
      - ibkr-network

  event-broker:
    build:
      context: .
      dockerfile: ./event-broker/Dockerfile
      args:
        VERSION: *system-version
    container_name: event-broker
    environment:      
      REDIS_HOST: redis
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      SERVICE_VERSION: *system-version
      REBALANCE_EVENT_SUBSCRIPTION_API_KEY: ${REBALANCE_EVENT_SUBSCRIPTION_API_KEY}
      TZ: America/New_York
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./event-broker/logs:/app/logs
      - ./accounts.yaml:/app/config/accounts.yaml
      - ./event-broker/config.yaml:/app/config/config.yaml
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ibkr-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "365"
    restart: unless-stopped      

  event-processor:
    build:
      context: ./event-processor
      args:
        VERSION: *system-version
    environment:
      IB_HOST: ibkr
      TRADING_MODE: ${TRADING_MODE:-paper}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      ALLOCATIONS_API_KEY: ${ALLOCATIONS_API_KEY}
      EXTENDED_HOURS_ENABLED: ${EXTENDED_HOURS_ENABLED:-false}
      SERVICE_VERSION: *system-version
      TZ: America/New_York
    volumes:
      - ./event-processor/config.yaml:/app/config/config.yaml
      - ./event-processor/logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ibkr-network
    depends_on:
      redis:
        condition: service_healthy
      ibkr:
        condition: service_healthy        
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "365"
    restart: on-failure

  management-service:
    build:
      context: ./management-service
      dockerfile: Dockerfile
      args:
        VERSION: *system-version
    container_name: management-service
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      REDIS_URL: redis://redis:6379/0
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      SERVICE_VERSION: *system-version
      TZ: America/New_York
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./management-service/logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ibkr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "365"
    restart: unless-stopped

  novnc:
    image: dougw/novnc:latest
    ports:
      - "127.0.0.1:6080:8081" 
    depends_on:
      - ibkr
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ibkr-network
    restart: unless-stopped
    environment:
      REMOTE_HOST: ibkr
      REMOTE_PORT: 5900
      TZ: America/New_York

