services:
  ibkr:
    image: ghcr.io/extrange/ibkr:stable  # Use 'stable' tag or specific version like 'latest'
    container_name: ibkr-gateway
    # args:
    #   ibc_version: 3.12.0    
    environment:
      - USERNAME=${IBKR_USERNAME}
      - PASSWORD=${IBKR_PASSWORD}
      - GATEWAY_OR_TWS=${GATEWAY_OR_TWS:-gateway}
      - TWOFA_TIMEOUT_ACTION=restart
      - TWS_SETTINGS_PATH=/home/ibkr/settings
      - IBC_TradingMode=${TRADING_MODE:-paper}      
      - IBC_AcceptNonBrokerageAccountWarning=yes
      - IBC_ReadOnlyApi=no
      - IBC_SecondFactorDevice=IB Key
      #- TZ=Asia/Singapore
    ports:
      - "127.0.0.1:6080:6080"  # noVNC browser access
      - "127.0.0.1:8888:8888"  # API access (paper trading)
      - "127.0.0.1:7497:7497"  # API access (paper trading - alternative port)
      - "127.0.0.1:7496:7496"  # API access (live trading)
    ulimits:
      nofile: 10000
    restart: unless-stopped
    volumes:
      - ibkr_settings:/home/ibkr/settings:rw
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/8888' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  rebalancer-api:
    build:
      context: ./rebalancer-api
      dockerfile: Dockerfile
    container_name: rebalancer-api
    environment:
      # IBKR credentials (sensitive data only)
      - IBKR_USERNAME=${IBKR_USERNAME}
      - IBKR_PASSWORD=${IBKR_PASSWORD}
      - TRADING_MODE=${TRADING_MODE:-paper}
      # API keys
      - ALLOCATIONS_API_KEY=${ALLOCATIONS_API_KEY}
    depends_on:
      ibkr:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: on-failure

  event-broker:
    build:
      context: ./event-broker
      dockerfile: Dockerfile
    container_name: event-broker
    depends_on:
      - rebalancer-api
    restart: unless-stopped

volumes:
  ibkr_settings:
