services:
  # Redis service
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # PostgreSQL service
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: portfolio_rebalancer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # IBKR Gateway (unchanged)
  ibkr:
    image: ghcr.io/extrange/ibkr:stable  # Use 'stable' tag or specific version like 'latest'
    container_name: ibkr-gateway
    # args:
    #   ibc_version: 3.12.0    
    environment:
      - USERNAME=${IBKR_USERNAME}
      - PASSWORD=${IBKR_PASSWORD}
      - GATEWAY_OR_TWS=${GATEWAY_OR_TWS:-gateway}
      - TWOFA_TIMEOUT_ACTION=restart
      - TWS_SETTINGS_PATH=/home/ibkr/settings
      - IBC_TradingMode=${TRADING_MODE:-paper}      
      - IBC_AcceptNonBrokerageAccountWarning=yes
      - IBC_ReadOnlyApi=no
      - IBC_SecondFactorDevice=IB Key
      #- TZ=Asia/Singapore
    ports:
      - "127.0.0.1:6080:6080"  # noVNC browser access
      - "127.0.0.1:8888:8888"  # API access (paper trading)
      - "127.0.0.1:7497:7497"  # API access (paper trading - alternative port)
      - "127.0.0.1:7496:7496"  # API access (live trading)
    ulimits:
      nofile: 10000
    restart: unless-stopped
    volumes:
      - ibkr_settings:/home/ibkr/settings:rw
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/8888' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  # Event-Processor service (replaces rebalancer-api)
  event-processor:
    build:
      context: ./event-processor
      dockerfile: Dockerfile
    container_name: event-processor
    environment:
      # IBKR credentials (sensitive data only)
      - IBKR_USERNAME=${IBKR_USERNAME}
      - IBKR_PASSWORD=${IBKR_PASSWORD}
      - TRADING_MODE=${TRADING_MODE:-paper}
      # API keys
      - ZEHNLABS_FINTECH_API_KEY=${ZEHNLABS_FINTECH_API_KEY}
      # Service discovery
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      ibkr:
        condition: service_healthy
    volumes:
      - ./event-processor/logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "365"
    restart: on-failure

  # Event-Broker service (modified)
  event-broker:
    build:
      context: ./event-broker
      dockerfile: Dockerfile
    container_name: event-broker
    environment:
      # Service discovery
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres
    volumes:
      - ./event-broker/logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "365"
    restart: unless-stopped

volumes:
  ibkr_settings:
  redis_data:
  postgres_data:
