services:
  ibkr:
    image: ghcr.io/extrange/ibkr:stable  # Use 'stable' tag or specific version like 'latest'
    container_name: ibkr-gateway
    environment:
      - USERNAME=${IBKR_USERNAME}
      - PASSWORD=${IBKR_PASSWORD}
      - GATEWAY_OR_TWS=${GATEWAY_OR_TWS:-gateway}
      - IBC_TradingMode=${TRADING_MODE:-paper}      
      - IBC_AcceptNonBrokerageAccountWarning=yes
      - IBC_ReadOnlyApi=no
      - IBC_SecondFactorDevice=IB Key
    ports:
      - "127.0.0.1:6080:6080"  # noVNC browser access
      - "127.0.0.1:8888:8888"  # API access (paper trading)
      - "127.0.0.1:7497:7497"  # API access (paper trading - alternative port)
      - "127.0.0.1:7496:7496"  # API access (live trading)
    ulimits:
      nofile: 10000
    restart: unless-stopped
    volumes:
      - ibkr_settings:/home/ibkr/settings

  rebalancer-api:
    build:
      context: ./rebalancer-api
      dockerfile: Dockerfile
    container_name: rebalancer-api
    environment:
      # IBKR credentials (sensitive data)
      - IBKR_HOST=ibkr
      - IBKR_PORT=${IBKR_PORT}
      - IBKR_USERNAME=${IBKR_USERNAME}
      - IBKR_PASSWORD=${IBKR_PASSWORD}
      - TRADING_MODE=${TRADING_MODE:-paper}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # API keys
      - ALLOCATIONS_API_KEY=${ALLOCATIONS_API_KEY}
      # FastAPI configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_WORKERS=1
    depends_on:
      - ibkr
    ports:
      - "8000:8000"
    restart: unless-stopped

  event-subscriber:
    build:
      context: ./event-subscriber
      dockerfile: Dockerfile
    container_name: event-subscriber
    environment:
      # Service Configuration
      - REBALANCER_API_URL=http://rebalancer-api:8000
      - REBALANCER_API_TIMEOUT=60
      # Ably Configuration
      - REALTIME_API_KEY=${REALTIME_API_KEY}
      # Application Settings
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ACCOUNTS_FILE=accounts.yaml
    depends_on:
      - rebalancer-api
    restart: unless-stopped

volumes:
  ibkr_settings:
