POST http://localhost:8000/api/v1/calculate
content-type: application/json

{
  "allocations": [
    {"symbol": "QQQ", "allocation": 0.6},
    {"symbol": "SPY", "allocation": 0.4}
  ]
}

GET http://localhost:8000/api/v1/account/info
