# Event Broker Service Configuration
# Routes events from Ably realtime messaging to Redis queue for processing
# Sensitive data should be set via environment variables

# Redis configuration for event queue
redis:
  host: redis              # Redis server hostname (overridden by REDIS_HOST env var)
  port: 6379              # Redis server port
  db: 0                   # Redis database number for event broker

# Application settings
application:
  accounts_file: "/accounts.yaml" # Path to account configuration file

# Event processor API configuration for health checks
rebalancer:
  api_url: "http://event-processor:8000"  # Event processor service URL for health checks
  timeout: 30                             # HTTP request timeout in seconds

