# Event Broker Service Configuration
# This file contains application configuration parameters
# Sensitive data (if any) should be set via environment variables

# Redis Configuration
redis:
  host: redis
  port: 6379
  db: 0

# PostgreSQL Configuration
postgresql:
  host: postgres
  port: 5432
  database: portfolio_rebalancer
  username: postgres
  password: postgres

# Ably Realtime Configuration
ably:
  api_key: "5L7t7A.AoDrNg:lXvCmY0oHKP08H_WevDb_ZdgtENDN4x_1LS_NfzvFho"  # This should be the actual non-user-configurable key

# Application Settings
application:
  log_level: "INFO"       # DEBUG, INFO, WARNING, ERROR, CRITICAL
  accounts_file: "accounts.yaml"

# Allocations API Configuration (for consistency with rebalancer-api)
allocations:
  base_url: "https://workers.fintech.zehnlabs.com/api/v1"

# Development/Testing Overrides (optional)
# Uncomment and modify for different environments
# development:
#   rebalancer_api:
#     url: "http://localhost:8000"
#   application:
#     log_level: "DEBUG"

# production:
#   application:
#     log_level: "WARNING"