# Event Broker Service Configuration
# Routes events from Ably realtime messaging to Redis queue for processing
# Sensitive data should be set via environment variables

# Redis configuration for event queue
redis:
  host: redis              # Redis server hostname (overridden by REDIS_HOST env var)
  port: 6379              # Redis server port
  db: 0                   # Redis database number for event broker

# Ably realtime messaging configuration
ably:
  api_key: "5L7t7A.AoDrNg:lXvCmY0oHKP08H_WevDb_ZdgtENDN4x_1LS_NfzvFho"  # Fixed API key for service

# Application settings
application:
  log_level: "INFO"             # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  accounts_file: "/accounts.yaml" # Path to account configuration file

# Strategy allocation API configuration
allocations:
  base_url: "https://workers.fintech.zehnlabs.com/api/v1/strategies"  # Base URL for strategy allocation API

# Event processor API configuration for health checks
rebalancer:
  api_url: "http://event-processor:8000"  # Event processor service URL for health checks
  timeout: 30                             # HTTP request timeout in seconds

