# Event Broker Service Configuration
# Routes events from Ably realtime messaging to Redis queue for processing
# Sensitive data should be set via environment variables

# Redis configuration for event queue
redis:
  host: redis              # Redis server hostname (overridden by REDIS_HOST env var)
  port: 6379              # Redis server port
  db: 0                   # Redis database number for event broker

# Application settings
application:
  accounts_file: "/app/config/accounts.yaml" # Path to account configuration file

