curl -X POST https://rest.ably.io/channels/etf-blend-100-20/messages \
     -u "5L7t7A.5-sblw:boStLcCJ1s7uO0e4J6E7zn6UFimIi_OrZrucMlb7KtM" \
     -H "Content-Type: application/json" \
     --data '{ "execution": "test" }'