# Management Service Configuration
# HTTP API for monitoring and managing the IBKR portfolio rebalancer system
# Sensitive data should be set via environment variables

# Redis configuration for accessing system state
redis:
  host: redis              # Redis server hostname (overridden by REDIS_HOST env var)
  port: 6379              # Redis server port
  db: 0                   # Redis database number for management service

# HTTP server configuration
server:
  host: "0.0.0.0"         # HTTP server bind address
  port: 8000              # HTTP server port

# Zehnlabs API configuration
zehnlabs:
  workers_api_url: "https://workers.fintech.zehnlabs.com/api/v1"  # Base URL for Zehnlabs Workers API
  api_timeout: 10         # HTTP request timeout in seconds

# Authentication configuration
authentication:
  clerk_frontend_api_url: "https://decent-heron-13.clerk.accounts.dev"  # Clerk Frontend API URL

# Application logging configuration
logging:
  level: INFO             # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: json            # Log format: json or text