# Redis configuration for event queue and caching
redis:
  host: redis              # Redis server hostname (overridden by REDIS_HOST env var)
  port: 6379              # Redis server port
  db: 0                   # Redis database number for event processor
  max_connections: 10     # Maximum Redis connection pool size

# Interactive Brokers API configuration
ibkr:
  # Connection settings (secrets come from environment variables)
  host: "ibkr"            # IBKR Gateway/TWS hostname (overridden by IB_HOST env var)
  
  # Connection retry configuration - handles network disconnections
  connection_retry:
    max_retries: 3        # Number of connection retry attempts before giving up
    delay: 5              # Seconds to wait between connection retry attempts
  
  # Order 
  order_retry:
    max_retries: 2        # Number of order retry attempts (kept low to avoid duplicates)
    delay: 1              # Seconds to wait between order retry attempts
  
  # Order completion timeout - how long to wait for orders to complete before failing event
  order_completion_timeout: 300  # Seconds to wait for sell orders to complete before timing out

# Event processing behavior configuration
processing:
  queue_timeout: 30           # Seconds to wait for new events from Redis queue (redis.brpop timeout)
  startup_max_attempts: 500   # Maximum startup retry attempts before failing
  startup_delay: 10           # Seconds between startup retry attempts
  startup_initial_delay: 30   # Initial delay at startup to allow other services to stabilize
  retry_delay_seconds: 60     # Seconds to wait before retrying failed events (prevents infinite loops)
  retry_check_interval: 60    # Seconds between checks for ready-to-retry retry events
  max_concurrent_events: 24   # Maximum number of events to process concurrently

# Strategy allocation API configuration
allocation:
  api_url: "https://workers.fintech.zehnlabs.com/api/v1/strategies"  # Base URL for strategy allocation API
  timeout: 30                                                        # HTTP request timeout in seconds

# Application logging configuration
logging:
  level: INFO             # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: json            # Log format: json or text