# IBKR Portfolio Rebalancer Configuration
# This file contains application configuration parameters
# Sensitive data (credentials, API keys) should be set via environment variables

# Interactive Brokers Configuration
ibkr:
  # Connection settings
  host: "ibkr"  # Docker container name, use "127.0.0.1" for local development
  port: 8888  # 8888 for gateway, 7497 for TWS paper, 7496 for TWS live
  gateway_or_tws: "gateway"  # "gateway" or "tws"
  
  # Retry configuration for IBKR connection
  connection_retry:
    max_retries: 3
    base_delay: 5          # seconds
    max_delay: 60          # seconds
    backoff_multiplier: 2.0
    jitter: true           # add randomization to prevent thundering herd
  
  # Retry configuration for market data operations
  market_data_retry:
    max_retries: 3
    base_delay: 2          # seconds
    max_delay: 30          # seconds
    backoff_multiplier: 1.5
    jitter: false          # market data timing is more critical
  
  # Retry configuration for order operations
  order_retry:
    max_retries: 2         # fewer retries for orders to avoid duplicates
    base_delay: 1          # seconds
    max_delay: 10          # seconds
    backoff_multiplier: 2.0
    jitter: false          # order timing is critical

# FastAPI Server Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 1

# Application Settings
application:
  log_level: "INFO"       # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Connection maintenance
  connection_check_interval: 30  # seconds between connection health checks
  
  # Startup configuration
  startup_max_attempts: 10       # max attempts during application startup
  startup_delay: 10              # seconds between startup attempts

# Development/Testing Overrides (optional)
# Uncomment and modify for different environments
# development:
#   ibkr:
#     host: "localhost"
#     port: 7497
#   application:
#     log_level: "DEBUG"

# production:
#   api:
#     workers: 4
#   application:
#     log_level: "WARNING"